### ISSUE TITLE
[koffi] Cannot build electron application when using koffi

### ISSUE THREAD

**Issue by MDransfeld** [Koromix/rygel#40]
Repo Steps:
https://github.com/MDransfeld/electron_koffi
(using electron-forge webpack-typescript template)

`npm i`
`npm run package`

Error:

```
An unhandled rejection has occurred inside Forge:
Error: Compilation errors in the main process: assets by status 21.9 KiB [cached] 1 asset
runtime modules 105 bytes 1 module
javascript modules 53.7 KiB
  cacheable modules 53.3 KiB
    modules by path ./node_modules/electron-squirrel-startup/ 18.7 KiB
      modules by path ./node_modules/electron-squirrel-startup/node_modules/debug/src/*.js 15 KiB 4 modules
      + 2 modules
    modules by path ./node_modules/koffi/src/ 32.8 KiB
      ./node_modules/koffi/src/koffi/src/index.js 2.46 KiB [built] [code generated]
      + 3 modules
    ./src/index.ts 1.71 KiB [built] [code generated]
  + 11 modules
./node_modules/koffi/package.json 658 bytes [optional] [built] [code generated]

ERROR in ./node_modules/koffi/src/koffi/src/index.js 32:15-41
Module not found: Error: Can't resolve '../package.json' in 'C:\Users\USER\Documents\tmp\koffi\node_modules\koffi\src\koffi\src'
resolve '../package.json' in 'C:\Users\USER\Documents\tmp\koffi\node_modules\koffi\src\koffi\src'
  using description file: C:\Users\USER\Documents\tmp\koffi\node_modules\koffi\package.json (relative path: ./src/koffi/src)
    using description file: C:\Users\USER\Documents\tmp\koffi\node_modules\koffi\package.json (relative path: ./src/koffi/package.json)
      no extension
        C:\Users\USER\Documents\tmp\koffi\node_modules\koffi\src\koffi\package.json doesn't exist
      .js
        C:\Users\USER\Documents\tmp\koffi\node_modules\koffi\src\koffi\package.json.js doesn't exist
      .ts
        C:\Users\USER\Documents\tmp\koffi\node_modules\koffi\src\koffi\package.json.ts doesn't exist
      .jsx
        C:\Users\USER\Documents\tmp\koffi\node_modules\koffi\src\koffi\package.json.jsx doesn't exist
      .tsx
        C:\Users\USER\Documents\tmp\koffi\node_modules\koffi\src\koffi\package.json.tsx doesn't exist
      .css
        C:\Users\USER\Documents\tmp\koffi\node_modules\koffi\src\koffi\package.json.css doesn't exist
      .json
        C:\Users\USER\Documents\tmp\koffi\node_modules\koffi\src\koffi\package.json.json doesn't exist
      as directory
        C:\Users\USER\Documents\tmp\koffi\node_modules\koffi\src\koffi\package.json doesn't exist
 @ ./src/index.ts 4:16-32
```

**Comment by Koromix** [comment]
I've made a PR on your test repo to use Koffi 2.3.10 (beta) and config electron-forge to include native files.

Seems to work! Well, your code crashes a bit later for other reasons I guess.

**Comment by insraq** [comment]
I am curious what's the issue here? I have used Koffi extensively with Electron (w/ Electron-Forge) and have no issues with it at all (Although I am using an older version of Koffi with some of my own patches).

Judging from this [changeset](https://github.com/Koromix/rygel/commit/e9e24b6cfa00182f5352152619ba9dab158c9b6a), I feel the "path probing" is probably not necessary? Using `path.resolve/path.join` should just work. Although whether it works with Electron ASAR can be tricky and needs to be tested

**Comment by Koromix** [comment]
It's not so much electron or electron-forge, but the use of webpack which causes the problem. 

First, webpack was getting confused by the fact that Koffi index.js was several directories deep (`src/koffi/src/index.js`) so I've changed the packaging process to move it to `src/index.js`.

Secondly, it does not understand the code that loads the native module and so, unless told somehow about them, they don't get packed at all. And then we have to somehow find them because they are not in the usual path.

**Comment by MDransfeld** [comment]
Thanks for the quick fix, version 2.3.10-beta.1 works for me (see this commit: https://github.com/MDransfeld/electron_koffi/commit/04de330db39a78bbf149bfc84d24383379f05882).

I just had to copy the relevant koffi.node files using the webpack copy plugin, as that doesn`t seem to work out of the box with the electron-forge template.

**Comment by 189** [comment]
> 

Your latest code is not work after `yarn package`,  but it perform well when `yarn start`. I think you miss this in `forge.config.js`:
```
const config: ForgeConfig = {
  packagerConfig: {},
  packagerConfig: {
    extraResource: ['node_modules/koffi/build']
  },
  ...
}
```

**Comment by 189** [comment]
> 

Your latest code is not work after yarn package, but it perform well when yarn start. I think you miss this in forge.config.js:
```
const config: ForgeConfig = {
  packagerConfig: {},
  packagerConfig: {
    extraResource: ['node_modules/koffi/build']
  },
  ...
}

**Comment by Koromix** [comment]
Looks resolved, closing!
