### ISSUE TITLE
[koffi] How to cast?

### ISSUE THREAD

**Issue by somanuell** [Koromix/rygel#47]
Hi,

Assume a C function int TheFunc( int arg1, void* buffer), with arg2 being an In Out pointer to various structures allocated by the caller, the precise type of the structure depending on the value or arg1.

In some cases, the pointer is simply a string. In other cases, it is a pointer to a real structure.

If I use func( 'int TheFunc( int, _Inout_ void*)' ) how can I call with arg2 being a string "A"?
I would like to cast to void* when calling, because I get the error "TypeError: Unexpected String value, expected void *"

**Comment by Koromix** [comment]
Try again with `Koffi 2.3.17`, which I've just released, and let me know how it goes ;)
Changelog: https://koffi.dev/changelog#koffi-2-3-17

**Comment by Koromix** [comment]
So in Koffi 2.3.17 I've improved the bahvior of strings with non-string C pointer types. You should be able to pass a string to a `void *` or `int8_t *` pointer ;)

If it's an *_Out_* or *_Inout_* parameter, pass it in a single element array. This is because JS parameters are always passed by values and strings are immutable, so Koffi uses single-elements arrays to fake mutable reference to primitive values.

An example:

```js
// Let's imagine the C function inverses the characters in-place
const ReverseChars = lib.func('void ReverseChars(_Inout_ char *str)');

let ptr = ['ABCD'];
ReverseChars(ptr);
console.log(ptr[0]); // DCBA
```

As far as objects go, you need to use `koffi.as()` to tell Koffi the actual type of the object you're trying to pass (since the C type is useless in this case).

Here is an (untested but you get the idea) example:

```js
const TypeEnum = {
    Vec: 0 // struct { int x; int y; }
    Rect: 1 // struct { int left; int top; int width; int height; }
};

const Vec = koffi.struct('Vec', { x: 'int', y: 'int' });
const Rect = koffi.struct('Vec', { left: 'int', top: 'int', width: 'int', height: 'int' });

const DoStuff = lib.func('void DoStuff(int type, _Inout_ void *ptr)');

DoStuff(TypeEnum.Vec, koffi.as({ x: 4, y: 2 }, 'Vec *'));
DoStuff(TypeEnum.Vec, koffi.as({ left: 1, top: 2, width: 3, height: 4 }, 'Rect *'));
```

You can find some documentation and examples here: https://koffi.dev/calls#polymorphic-parameters

**Comment by somanuell** [comment]
Marvellous. Thank you so much!

I will test and let you know.

Additional question, not really important: do you read your emails on protonmail.com?

**Comment by somanuell** [comment]
First result (passing a string):
Alas, if I need the ` _Inout_ void *` prototyping (and I need it) I can't find a way to use a sting as an argument...
The `let ptr=['A']` gives me `TypeError: Cannot pass ambiguous value to void *, use koffi.as()`
Passing `koffi.as(ptr,'void*')` gives same error.
Only way I found ok, is to use `_In_` instead of ` _Inout_`
But that's not a real problem! I just have to declare a dummy struct...

**Comment by somanuell** [comment]
I'll test the second thing (using various structures) later this weekend. Thanks again!

**Comment by somanuell** [comment]
`2.3.19` works like a charm.
Anyway, I should have read the documentation better on koffi.dev...
