### ISSUE TITLE
[koffi]: Cannot use more than 16 output parameters

### ISSUE THREAD

**Issue by TheCleric** [Koromix/rygel#67]
Using koffi, I am trying to call a function (that I do not have control over) in a shared library, and it has 23 output variables that the function takes as parameters.

However, I get the following when trying to call the code:

`TypeError: Functions cannot have more than 16 output parameters`

Looking into it, this seems to be an artificial (though likely for a reason) limitation imposed by the MaxOutParameters value in the src.

Is this limit for a reason? Could it possibly be eliminated, raised, or made configurable?

Thanks!

**Comment by Koromix** [comment]
I like to put limits on things, especially because you can use that to avoid many dynamic allocations.

The total number of parameters is limited to 32, and I felt like no function would ever need more than 16 output parameters, but I was obviously wrong :)

I've removed this limit (but kept the total number of parameters to 32) in Koffi 2.5.6, which will be released soon, once the tests and the builds are done on all supported platforms (takes 10-15 minutes).

**Comment by Koromix** [comment]
Koffi 2.5.6 has been released :)
Changelog here: https://koffi.dev/changelog
